export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ||
  "https://acomacjoinville.com.br"
).replace(/\/$/, "");

export const SITE_NAME = "ACOMAC Joinville";

export const SITE_SHORT_NAME = "ACOMAC";

export const SITE_DEFAULT_TITLE =
  "ACOMAC Joinville — Associação dos Comerciantes de Material de Construção";

export const SITE_DEFAULT_DESCRIPTION =
  "A maior associação do varejo de material de construção de Santa Catarina. Desde 1983 em Joinville, unindo lojistas com cursos, eventos, convênios e benefícios exclusivos.";

export const SITE_KEYWORDS = [
  "ACOMAC",
  "ACOMAC Joinville",
  "associação material de construção",
  "varejo construção civil SC",
  "material de construção Joinville",
  "FENAC",
  "Academia da Construção",
  "convênios construção civil",
  "eventos construção civil SC",
  "lojistas construção Joinville",
];

export const SITE_LOCALE = "pt_BR";
export const SITE_LANG = "pt-BR";

// Dynamic OG image generated by src/app/opengraph-image.tsx (next/og).
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "ACOMAC Joinville — Associação dos Comerciantes de Material de Construção",
};

export function absoluteUrl(path: string = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

import type { Metadata } from "next";

export function buildPageMetadata({
  title,
  description,
  path,
  image,
  noIndex,
  type = "website",
  publishedTime,
  modifiedTime,
  authors,
  tags,
}: {
  title: string;
  description: string;
  path: string;
  image?: { url: string; width?: number; height?: number; alt?: string };
  noIndex?: boolean;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  tags?: string[];
}): Metadata {
  const canonical = absoluteUrl(path);
  const ogImage = image
    ? {
        url: image.url,
        width: image.width ?? DEFAULT_OG_IMAGE.width,
        height: image.height ?? DEFAULT_OG_IMAGE.height,
        alt: image.alt ?? title,
      }
    : DEFAULT_OG_IMAGE;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      locale: SITE_LOCALE,
      url: canonical,
      siteName: SITE_NAME,
      title,
      description,
      images: [ogImage],
      ...(type === "article"
        ? { publishedTime, modifiedTime, authors, tags }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage.url],
    },
    robots: noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true },
  };
}
